name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"
          cache: true

      - name: Show Flutter version
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Show Android project
        run: |
          ls -R android
          cat android/settings.gradle.kts
          cat android/build.gradle.kts
          cat android/app/build.gradle.kts

      - name: Build release APK
        run: flutter build apk --release -v

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: kadd-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
